### ISSUE TITLE
PNG images with bit depth other than 32 gives black background.

### ISSUE THREAD

**Issue by MikuAuahDark** [DeadSix27/waifu2x-converter-cpp#107]
```
w2x -i ef_313_005.png -m scale --scale_ratio 2 -o ef_313_005_w2x.png
```

`ef_313_005.png`  
![ef_313_005](https://user-images.githubusercontent.com/7500438/53566579-8b056d80-3b97-11e9-94f0-34ba5e6474bf.png)

Note that the PNG image only has bit depth of 8, but it has transparency. Issue present in v5.2.3 (uses OpenCL, can't use CUDA due to #100).

**Comment by cjmaxik** [comment]
Same thing.
![Alice](https://user-images.githubusercontent.com/1501705/57119954-41145000-6db1-11e9-8938-e7c9989b3ede.png)
![Alice@2x](https://user-images.githubusercontent.com/1501705/57119956-41145000-6db1-11e9-9601-eeeef2d8e76c.png)

Image © 2D Boy, LLC, 2008

**Comment by MikuAuahDark** [comment]
A solution I can think is to convert the 8-bit PNG to 32-bit PNG internally inside waifu2x first then do the upscaling. Is this feasible solution?

**Comment by cjmaxik** [comment]
I did it using `imagemagick`:

`.\magick.exe -define png:format=png32 $($_.FullName) $($_.FullName)`

**Comment by Kattus** [comment]
@MikuAuahDark that is what waifu2x-caffe does afaik, at least the output is RGB32.

**Comment by MikuAuahDark** [comment]
What I mean is that it maybe feasible to convert the image implicitly first.

**Comment by YukihoAA** [comment]
8bit png have 4 channels.. but.. why?????

i tried to convert 8bit bgr png to 32bit brga but i have no idea how to convert them in opencv...

**Comment by MikuAuahDark** [comment]
What I mean with 8bit PNG is, that PNG uses color palette which also has transparency. If you check the image sample I posted above in Windows Explorer properties, you can see the "Bit Depth" is 8, not 32.

**Comment by YukihoAA** [comment]
I know your image is 8-bit png and it has transparency, but i mean i cannot find way to convert 8-bit png to 32bit png in opencv..

**Comment by DeadSix27** [comment]
https://docs.opencv.org/3.1.0/d3/d63/classcv_1_1Mat.html#a3f356665bb0ca452e7d7723ccac9a810
`m | output matrix; if it does not have a proper size or type before the operation, it is reallocated.`

Make sure you set scale_factor when downscaling matrix.

e.g: convertTo(mat, CV_8U, 0.002);

CV_8U = unsigned 8bit

I assume this is the right function to convert ?

**Comment by YukihoAA** [comment]
cv::Mat input, output;
	
	input = cv::imread("test_8bit.png", cv::IMREAD_UNCHANGED);
	
	std::cout << input.rows << ", "  << input.cols << ", " << input.channels() << ", " << input.depth() << std::endl;
	
	input.convertTo(output, CV_32FC4);
	
	cv::cvtColor(output, output, cv::COLOR_BGR2BGRA);
	
	cv::imwrite("test_out.png", output);

but test_out.png has no alpha channel

**Comment by DeadSix27** [comment]
We have to split off the alpha channel and add it back at the end, which Is probably impossible because we alter the original image and its size a lot?

**Comment by DeadSix27** [comment]
See also: <https://stackoverflow.com/questions/20229577/opencv-cvcvtcolor-drops-alpha-channel-how-to-keep-alpha-data>

**Comment by YukihoAA** [comment]
ok i got clue on this issue.

this issue occurs because w2x does not recognize 8-bit png as png (what????)

I fixed issue but i need more time to test.

we don't even need to convert to 32bit it will do automatically lol

I'll make changes soon.. may be tomorrow.

**Comment by DeadSix27** [comment]
This was actually still an issue with indexed + alpha images, but that will be fixed with: #164
